export const CHANGE_PSEUDO_ACTION = "CHANGE_PSEUDO_ACTION"
export const CHANGE_PASSWORD_ACTION = "CHANGE_PASSWORD_ACTION"
export const LOGIN_ACTION = "LOGIN_ACTION"
export const SHOW_PASSWORD_ACTION = "SHOW_PASSWORD_ACTIONS"

export const CHANGE_DASHBOARD_PAGE_ACTION = "CHANGE_DASHBOARD_PAGE_ACTION"
export const LOGOUT_ACTION = "LOGOUT_ACTION"

export const GET_STATISTICS_ACTION = "GET_STATISTICS_ACTION"

export const GET_SPECIFIC_SURVEY_ACTION = "GET_SPECIFIC_SURVEY_ACTION"

export const GET_SONDAGE_DATA_ACTION = "GET_SONDAGE_DATA_ACTION"
export const CHANGE_SONDAGE_SELECTION_ACTION = "CHANGE_SONDAGE_SELECTION_ACTION"
export const POST_SURVEY_ACTION = "POST_SURVEY_ACTION"

export const UPLOAD_USERLIST_ACTION = "UPLOAD_USERLIST_ACTION"
export const POST_USER_ACTION = "POST_USER_ACTION"

