export const USER_CHANGE_PSEUDO_ACTION = "USER_CHANGE_PSEUDO_ACTION"
export const USER_CHANGE_PASSWORD_ACTION = "USER_CHANGE_PASSWORD_ACTION"
export const USER_LOGIN_ACTION = "USER_LOGIN_ACTION"
export const USER_SHOW_PASSWORD_ACTION = "USER_SHOW_PASSWORD_ACTIONS"
export const TOGGLE_DRAWER_ACTION = "TOGGLE_DRAWER_ACTION"

export const SWITCH_PAGE_ACTION = "SWITCH_PAGE_ACTION"
export const REDIRECT_TO_LOGIN_ACTION = "REDIRECT_TO_LOGIN_ACTION"
export const GET_USER_ACTION = "GET_USER_ACTION"